language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

sudo: false

cache: cargo

install:
  - (rustfmt -V || cargo install rustfmt -f --vers 0.9.0)
  - PATH=$PATH:/home/travis/.cargo/bin

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
