language: rust

rust:
  - 1.41.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

sudo: false

cache: cargo

install:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then rustup component add rustfmt; fi
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then rustup component add clippy; fi

script:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then cargo fmt --all -- --check; fi
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then cargo clippy -- -D warnings; fi
  - cargo build --verbose
  - cargo test --verbose

deploy:
  provider: cargo
  token:
    secure: "UrA2NUCMlqeikvD11VYHvWB3pXu6Ozl7tizoXhtVzr0QyWhj9+fl+UPrRTlOOGaZVgIQhcul2/PvhVZjsd5c5iIy04c0rAKNljjk7oYGyySF71Qfzy55hkyB8CIYSobMe6ne4cgNPS3WGclF65SHzcV7P6U9U4j8qaF8b43A8Ad0c5UzPkmiYmolyB8fQVeb9MEedvaiqzWqRSbYqEEEhlAdNjkITpvrdGKBp8WJk0CteeeloKFj34aNDQVZJv9gTIR07Jch8FqqX4UoKqixDUSCVEll5ze4umsVQ+Gni829usGXCZG3OjR/GCANB7PqGxnjTsox2qcWZxfsT3pSLdQHQlJSkCHwV4OrOk30JV3QdaSPPMQsbB3cMoEcqhO32zfNFKMVGRvYW6AC+zzUP9i7jmy4IE4+sYOXbmx80fgKzgUlUnDDM2ItJlO0CKY4f+z7zkRHeYwouYKEZGN8bUtIEpuvMaBBzvV4mshrOuu23OXLCsr52eQqyeS0sewg9gpxeijVqBUeVYIK/1PXCeQXWntjHifNr7HJEyK/Cv8AuzbQR/ooRdQUaPcAveSi3/O1xPvWDf1Z4fO6WsuCCm1DWe0YPJNBJjleG9b6cPiqrkY9d9odq2Ob+I8QRUVTaTDQ7AZ6RzeE9UBWZ3Q2H+PHj9thtAjdKWK1ynRvkQk="
  on:
    tags: true
    rust: stable
