language: rust

rust:
  - 1.17.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

sudo: false

cache: cargo

install:
  - (cargo install rustfmt || true)
  - PATH=$PATH:/home/travis/.cargo/bin

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
